language: node_js
node_js:
  - stable

script:
  - make lint
  - make test

addons:
  code_climate:

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
